-- Hand-written migration (architecture v4.1, Checkpoint 4F).
-- NOT generated by `prisma migrate dev` — contains data backfills and
-- PostgreSQL-specific objects (deferred constraint trigger, partial unique
-- index) that Prisma's schema diffing cannot safely produce.
--
-- Apply via: prisma db execute --file <this file> --schema prisma/schema.prisma
-- Then register via: prisma migrate resolve --applied 20260829120000_add_variant_inventory_foundation
-- Never via `prisma migrate dev` / `migrate reset` / `db push` on this environment.
--
-- Ordering contract:
--   1) create every new table/enum with no data dependency
--   2) create ProductVariant (needs products to already exist for its FK)
--   3) create the remaining join/leaf tables
--   4) create the deferred trigger (before any real writes touch PVOV)
--   5) create the partial unique index for default Location
--   6) backfill: Location -> ProductVariant (copies products.price) -> Inventory
--   7) only once every existing product has a variant carrying its price
--      forward, drop products.price
--
-- Entire migration runs as a single transaction: either every step applies,
-- or none do. products.price is never dropped before its value has been
-- copied into product_variants.price (backfill in step 14 happens strictly
-- before the DROP COLUMN in step 16).

BEGIN;

-- =========================================================================
-- 1. ProductVariantStatus enum
-- =========================================================================
CREATE TYPE "ProductVariantStatus" AS ENUM ('active', 'archived');

-- =========================================================================
-- Product needs (id, tenantId) available as a composite FK target for
-- ProductVariant and ProductOption below (not present in the original
-- Checkpoint 4C migration). Structural only — no data change.
-- =========================================================================
ALTER TABLE "products" ADD CONSTRAINT "products_id_tenantId_key" UNIQUE ("id", "tenantId");

-- =========================================================================
-- 2. VariantOption
-- =========================================================================
CREATE TABLE "variant_options" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "name" TEXT NOT NULL,

    CONSTRAINT "variant_options_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "variant_options_tenantId_name_key" ON "variant_options"("tenantId", "name");
CREATE UNIQUE INDEX "variant_options_id_tenantId_key" ON "variant_options"("id", "tenantId");
CREATE INDEX "variant_options_tenantId_idx" ON "variant_options"("tenantId");

ALTER TABLE "variant_options"
  ADD CONSTRAINT "variant_options_tenantId_fkey"
  FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- =========================================================================
-- 3. VariantOptionValue
-- =========================================================================
CREATE TABLE "variant_option_values" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "variantOptionId" TEXT NOT NULL,
    "value" TEXT NOT NULL,

    CONSTRAINT "variant_option_values_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "variant_option_values_tenantId_variantOptionId_value_key" ON "variant_option_values"("tenantId", "variantOptionId", "value");
CREATE UNIQUE INDEX "variant_option_values_id_tenantId_key" ON "variant_option_values"("id", "tenantId");
CREATE UNIQUE INDEX "variant_option_values_id_variantOptionId_key" ON "variant_option_values"("id", "variantOptionId");

ALTER TABLE "variant_option_values"
  ADD CONSTRAINT "variant_option_values_variantOptionId_tenantId_fkey"
  FOREIGN KEY ("variantOptionId", "tenantId") REFERENCES "variant_options"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;

-- =========================================================================
-- 4. Location (isDefault, isActive, timestamps)
-- =========================================================================
CREATE TABLE "locations" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "locations_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "locations_tenantId_name_key" ON "locations"("tenantId", "name");
CREATE UNIQUE INDEX "locations_id_tenantId_key" ON "locations"("id", "tenantId");
CREATE INDEX "locations_tenantId_idx" ON "locations"("tenantId");

ALTER TABLE "locations"
  ADD CONSTRAINT "locations_tenantId_fkey"
  FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- =========================================================================
-- 5. ProductVariant (tenantId, productId, sku, price, status,
--    combinationKey, timestamps, all required unique indexes)
-- =========================================================================
CREATE TABLE "product_variants" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "sku" TEXT,
    "price" INTEGER NOT NULL,
    "status" "ProductVariantStatus" NOT NULL DEFAULT 'active',
    "combinationKey" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "product_variants_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "product_variants_tenantId_sku_key" ON "product_variants"("tenantId", "sku");
CREATE UNIQUE INDEX "product_variants_tenantId_productId_combinationKey_key" ON "product_variants"("tenantId", "productId", "combinationKey");
CREATE UNIQUE INDEX "product_variants_id_tenantId_key" ON "product_variants"("id", "tenantId");
CREATE UNIQUE INDEX "product_variants_id_productId_key" ON "product_variants"("id", "productId");
CREATE INDEX "product_variants_productId_idx" ON "product_variants"("productId");

ALTER TABLE "product_variants"
  ADD CONSTRAINT "product_variants_productId_tenantId_fkey"
  FOREIGN KEY ("productId", "tenantId") REFERENCES "products"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;

-- =========================================================================
-- 6. ProductOption
-- =========================================================================
CREATE TABLE "product_options" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "variantOptionId" TEXT NOT NULL,

    CONSTRAINT "product_options_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "product_options_productId_variantOptionId_key" ON "product_options"("productId", "variantOptionId");
CREATE INDEX "product_options_tenantId_idx" ON "product_options"("tenantId");

ALTER TABLE "product_options"
  ADD CONSTRAINT "product_options_productId_tenantId_fkey"
  FOREIGN KEY ("productId", "tenantId") REFERENCES "products"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "product_options"
  ADD CONSTRAINT "product_options_variantOptionId_tenantId_fkey"
  FOREIGN KEY ("variantOptionId", "tenantId") REFERENCES "variant_options"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;

-- =========================================================================
-- 7. ProductVariantOptionValue
-- =========================================================================
CREATE TABLE "product_variant_option_values" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "productVariantId" TEXT NOT NULL,
    "variantOptionId" TEXT NOT NULL,
    "variantOptionValueId" TEXT NOT NULL,

    CONSTRAINT "product_variant_option_values_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "product_variant_option_values_productVariantId_variantOpt_key" ON "product_variant_option_values"("productVariantId", "variantOptionId");
CREATE INDEX "product_variant_option_values_tenantId_idx" ON "product_variant_option_values"("tenantId");
CREATE INDEX "product_variant_option_values_variantOptionValueId_idx" ON "product_variant_option_values"("variantOptionValueId");

ALTER TABLE "product_variant_option_values"
  ADD CONSTRAINT "product_variant_option_values_productVariantId_tenantId_fkey"
  FOREIGN KEY ("productVariantId", "tenantId") REFERENCES "product_variants"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "product_variant_option_values"
  ADD CONSTRAINT "product_variant_option_values_productVariantId_productId_fkey"
  FOREIGN KEY ("productVariantId", "productId") REFERENCES "product_variants"("id", "productId") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "product_variant_option_values"
  ADD CONSTRAINT "product_variant_option_values_productId_variantOptionId_fkey"
  FOREIGN KEY ("productId", "variantOptionId") REFERENCES "product_options"("productId", "variantOptionId") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "product_variant_option_values"
  ADD CONSTRAINT "product_variant_option_values_variantOptionValueId_tenant_fkey"
  FOREIGN KEY ("variantOptionValueId", "tenantId") REFERENCES "variant_option_values"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "product_variant_option_values"
  ADD CONSTRAINT "product_variant_option_values_variantOptionValueId_option_fkey"
  FOREIGN KEY ("variantOptionValueId", "variantOptionId") REFERENCES "variant_option_values"("id", "variantOptionId") ON DELETE CASCADE ON UPDATE CASCADE;

-- =========================================================================
-- 8. Inventory
-- =========================================================================
CREATE TABLE "inventory" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "productVariantId" TEXT NOT NULL,
    "locationId" TEXT NOT NULL,
    "onHand" INTEGER NOT NULL DEFAULT 0,
    "reserved" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "inventory_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "inventory_tenantId_locationId_productVariantId_key" ON "inventory"("tenantId", "locationId", "productVariantId");

ALTER TABLE "inventory"
  ADD CONSTRAINT "inventory_productVariantId_tenantId_fkey"
  FOREIGN KEY ("productVariantId", "tenantId") REFERENCES "product_variants"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "inventory"
  ADD CONSTRAINT "inventory_locationId_tenantId_fkey"
  FOREIGN KEY ("locationId", "tenantId") REFERENCES "locations"("id", "tenantId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- =========================================================================
-- 9. (all indexes/FKs above are already attached inline with each table)
-- =========================================================================

-- =========================================================================
-- 10 & 11. Combination-key trigger function + DEFERRABLE INITIALLY DEFERRED
--    constraint trigger. Mirrors the mechanism verified in the Step 2
--    pre-flight test (test-duplicate-combination.js): recomputes
--    product_variants.combinationKey from the join rows on
--    INSERT/UPDATE/DELETE, deferred to COMMIT so multi-row inserts within
--    one transaction see their final combination before the unique index
--    is checked.
-- =========================================================================
CREATE OR REPLACE FUNCTION recompute_product_variant_combination_key() RETURNS TRIGGER AS $$
DECLARE
  v_key TEXT;
BEGIN
  IF TG_OP IN ('INSERT', 'UPDATE') THEN
    SELECT string_agg("variantOptionId" || ':' || "variantOptionValueId", '|' ORDER BY "variantOptionId")
      INTO v_key FROM "product_variant_option_values" WHERE "productVariantId" = NEW."productVariantId";
    UPDATE "product_variants" SET "combinationKey" = COALESCE(v_key, '') WHERE "id" = NEW."productVariantId";
  END IF;
  IF TG_OP IN ('UPDATE', 'DELETE') THEN
    IF TG_OP = 'DELETE' OR OLD."productVariantId" IS DISTINCT FROM NEW."productVariantId" THEN
      SELECT string_agg("variantOptionId" || ':' || "variantOptionValueId", '|' ORDER BY "variantOptionId")
        INTO v_key FROM "product_variant_option_values" WHERE "productVariantId" = OLD."productVariantId";
      UPDATE "product_variants" SET "combinationKey" = COALESCE(v_key, '') WHERE "id" = OLD."productVariantId";
    END IF;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER trg_recompute_combination_key
  AFTER INSERT OR UPDATE OR DELETE ON "product_variant_option_values"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION recompute_product_variant_combination_key();

-- =========================================================================
-- 12. Partial unique index: exactly one default Location per tenant.
--    Not representable in schema.prisma (see the comment above the
--    Location model) — hand-written here as documented.
-- =========================================================================
CREATE UNIQUE INDEX "locations_one_default_per_tenant"
  ON "locations"("tenantId")
  WHERE "isDefault" = true;

-- =========================================================================
-- 13. Backfill: one default Location per existing Tenant.
--    Runs after the partial unique index exists, so if this INSERT ever
--    tried to create two defaults for the same tenant it would fail loudly
--    (23505) rather than silently violating the invariant.
-- =========================================================================
INSERT INTO "locations" ("id", "tenantId", "name", "isDefault", "isActive", "createdAt", "updatedAt")
SELECT gen_random_uuid()::text, "id", 'Default Location', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM "tenants";

-- =========================================================================
-- 14. Backfill: one ProductVariant per existing Product, preserving
--    products.price. combinationKey = '' (simple product, no options).
--    This is the step that carries products.price forward before it is
--    dropped in step 16 — must run before that DROP COLUMN, never after.
-- =========================================================================
INSERT INTO "product_variants" ("id", "tenantId", "productId", "sku", "price", "status", "combinationKey", "createdAt", "updatedAt")
SELECT gen_random_uuid()::text, "tenantId", "id", NULL, "price", 'active', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM "products";

-- =========================================================================
-- 15. Backfill: one Inventory row per newly-created ProductVariant, at
--    that tenant's default Location, onHand = 0, reserved = 0.
-- =========================================================================
INSERT INTO "inventory" ("id", "tenantId", "productVariantId", "locationId", "onHand", "reserved", "createdAt", "updatedAt")
SELECT gen_random_uuid()::text, pv."tenantId", pv."id", loc."id", 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM "product_variants" pv
JOIN "locations" loc ON loc."tenantId" = pv."tenantId" AND loc."isDefault" = true;

-- =========================================================================
-- 16. Only after every existing Product has a ProductVariant carrying its
--    price forward (step 14 backfill above): drop products.price.
-- =========================================================================
ALTER TABLE "products" DROP COLUMN "price";

COMMIT;
