import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import { getCurrentTenant } from './_storefront/get-current-tenant';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export async function generateMetadata(): Promise<Metadata> {
  const tenant = await getCurrentTenant();
  if (!tenant) {
    return {
      title: 'Create Next App',
      description: 'Generated by create next app',
    };
  }

  return {
    title: tenant.branding?.storeName || tenant.name,
    description: `${tenant.branding?.storeName || tenant.name} storefront`,
    icons: tenant.branding?.faviconUrl ? { icon: tenant.branding.faviconUrl } : undefined,
  };
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <ClerkProvider signInUrl="/sign-in">
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    </ClerkProvider>
  );
}
